---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build container
    image: plugins/docker
    pull: never
    settings:
      registry: gitea.local.nevermad.de
      username: DeLachs
      password:
        from_secret: gitea_token
      repo: gitea.local.nevermad.de/${DRONE_REPO,,}
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}

---
kind: pipeline
type: docker
name: redeploy

clone:
  disable: true

steps:
  - name: redeploy
    image: docker.io/alpine
    commands:
      - apk --update add curl
      - "curl --request POST https://portainer.local.nevermad.de/api/stacks/webhooks/1de994ac-4434-412c-ba7a-e8407c918cc1"

depends_on:
  - build