version: '3.9'
services:
  lachs-bot:
    image: ghcr.io/delachs/lachs-bot-js:latest
    container_name: lachs-bot
    restart: unless-stopped
    volumes:
      - ./lachs-bot-js/:/app/data
    env_file:
      - ./.env
